# Generated by Django 3.1.3 on 2020-12-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientpreference',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
    ]
