# Generated by Django 3.1.1 on 2020-11-03 14:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='reports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='review_comment_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='food',
            name='nutrition',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='food',
            name='tag',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='food',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='foodinstance',
            name='expiry_date',
            field=models.DateField(default=datetime.date(2020, 11, 3)),
        ),
        migrations.AlterField(
            model_name='foodinstance',
            name='nutrition_facts',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='foodinstance',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='count_ratings',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='rating',
            field=models.FloatField(default='0.0'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tag',
            field=models.JSONField(default=None),
        ),
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='reports',
            field=models.IntegerField(default=0),
        ),
    ]
