# Generated by Django 3.1.3 on 2020-12-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201210_0311'),
    ]

    operations = [

        migrations.AddField(
            model_name='searchsetting',
            name='fridge_able',
            field=models.BooleanField(default=False),
        ),
    ]
