# Generated by Django 3.1.3 on 2020-11-09 08:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0002_auto_20201103_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=80)),
                ('quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(default=datetime.date(2020, 11, 9))),
                ('nutrition_facts', models.JSONField(blank=True, default=None, null=True)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridgeitem_food_type', to='backend.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fridgeitem_user_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FoodInstance',
        ),
    ]
