# Generated by Django 3.1.3 on 2020-12-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_ingredient_ingredientpreference_labelpreference_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fridgeitem',
            name='food',
        ),
        migrations.RemoveField(
            model_name='fridgeitem',
            name='nutrition_facts',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='food',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
