# Generated by Django 3.1.3 on 2020-12-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201201_1818'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientpreference',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='ingredientpreference',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='labelpreference',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
