# Generated by Django 3.1.3 on 2020-11-09 08:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201109_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeitem',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 9, 8, 39, 25, 366694, tzinfo=utc)),
        ),
    ]
