# Generated by Django 3.1.3 on 2020-11-10 12:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20201109_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AddField(
            model_name='review',
            name='author_name',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 10, 12, 36, 49, 644315, tzinfo=utc)),
        ),
    ]
