# Generated by Django 3.1.3 on 2020-12-10 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_commentprofile_reviewprofile'),
        ('backend', '0005_auto_20201207_0709'),
    ]

    operations = [
    ]
