# Generated by Django 3.1.3 on 2020-11-10 12:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20201110_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 10, 12, 38, 27, 495114, tzinfo=utc)),
        ),
    ]
