# Generated by Django 3.1.3 on 2020-11-10 19:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20201110_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='fridgeitem',
            name='expiry_date',
            field=models.DateField(default=datetime.datetime(2020, 11, 10, 19, 42, 39, 371033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='review',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
