# Generated by Django 3.1.2 on 2020-11-19 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201110_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeitem',
            name='expiry_date',
            field=models.CharField(default='2020-11-19 02:47:51.798155+00:00', max_length=12),
        ),
    ]
