# Generated by Django 3.1.3 on 2020-11-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201118_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fridgeitem',
            name='expiry_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
