# Generated by Django 3.1.3 on 2020-11-27 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20201127_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='time_posted',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
