# Generated by Django 3.1.3 on 2020-11-28 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201119_0247'),
        ('backend', '0010_auto_20201127_1415'),
    ]

    operations = [
    ]
