services:
  - postgresql
matrix:
  include:
    - language: node_js
      node_js: '12'
      python: '3.7'
      cache:
        - yarn: true
        - pip: true
      addons:
        sonarcloud:
          organization: "swsnu"
          token:
            secure: "kP+U7hN4tLvG1JrQOQbiI1xyWxaonh4b9Ej3oVRa0EhlnQaib6DD8tIYk9ecIXzI31F3TCc8spdRSa3FFelNHZ6SdgZc/i9FWSFxsci63mcZGb2jIWmjIV3nVypfw3M51HyYRJElz5AEEA84LSitdArOa1//HtJ4wziFWreBOxnp4LYgKYldiYG9DiPTyx2oOqgb0pHQCTB8jOow7GQSIGCR7u2EiHyWmUJdW8+791Qz4okAp3t0usoKTatMDcs+ArDAMeofW0QruTlq85gmA3NbAppQNDi4KDy3cs4DUHkmmvePO9fV36O1ii4l+Ty2PoI+RslCMPq3e2dTSVNtKlvOGjF6u8nJV/T2+DzCz7IBiY4+vodqUmRv8jwD3UTUBtZALz2qbnHMy2BBeFtLIlq1gRwb6xBbQF49uclHjMGOMj4I4uiB742W8lEGA2iz+WwImvuAXHccJQmxp/vhxo31yRm0hlxUObVpvV+INEoJD1r/dQwPfXgZ3aPjZgDKwH2IMcZOQGmbagiR0jibzUJ13sT/6EDxHfouTKKUy0IR3JMdATayEWWE623p8txCpjunR5RpdW4Elw9ppSk5AKemxs4vXFp4SetAtTEL2KG550GMics1Dw5vD0xda8gaWBly444df+HyMifanrmdmNOx8sLYjwFLW8n9cYDNKhk="
      install:
        - cd frontend
        - yarn install
        - yarn global add coveralls
        - gem install coveralls-lcov
        - cd ..
        - cd backend
        - source ~/virtualenv/python3.7/bin/activate
        - pip install -r requirements.txt
        - pip install coveralls
        - pip install psycopg2
        - pip install django-extensions
        - cd ..
      before_script:
        - psql -c "CREATE DATABASE fridge_db;" -U postgres
      env:
        global:
          - PGUSER=postgres
          - PGPORT=5432
      script:
        - cd frontend
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false --passWithNoTests --silent
        - cd ..
        - cd backend
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='./backend/' manage.py test backend.tests --keepdb
        - coverage xml
        - cd ..
        - sonar-scanner
        - cd frontend
        - coveralls-lcov -v -n coverage/lcov.info > coverage.json
        - cd ..
        - cd backend
        - coveralls --merge=../frontend/coverage.json
        - cd ..

    - language: node_js
      node_js: '12'
      cache:
        - yarn: true
      before_install:
        - cd frontend
      install:
        - npm install
        - npm install coveralls
      script:
        - ./node_modules/.bin/eslint src/
        - yarn test --coverage --watchAll=false --passWithNoTests
        - cd ..

    - language: python
      python: '3.8'
      cache:
        - pip: true
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
        - pip install coveralls
        - pip install psycopg2
        - pip install django-extensions
      before_script:
        - psql -c "CREATE DATABASE fridge_db;" -U postgres
      env:
        global:
          - PGUSER=postgres
          - PGPORT=5432
      script:
        - pylint **/*.py --load-plugins pylint_django
        - coverage run --source='./backend/' manage.py test backend.tests --keepdb
        - coverage report -m
