# Generated by Django 3.1.3 on 2020-11-28 07:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_auto_20201128_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='nutrition',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='tag',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='diet_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='health_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='searchsetting',
            name='diet_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='searchsetting',
            name='health_labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, size=None),
        ),
    ]
