# Generated by Django 3.1.3 on 2020-11-28 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0013_auto_20201128_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.JSONField(default=None, null=True),
        ),
    ]
